apiVersion: apps/v1
kind: Deployment
metadata:
  name: classification-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classification-explorer
  template:
    metadata:
      labels:
        app: classification-explorer
    spec:
      containers:
        - name: classification-explorer
          image: unece/classification-explorer:latest
          env:
            - name: ENDPOINT
              value: 'https://graphdb.linked-open-statistics.org/repositories/classifications'
            - name: DEPLOY_MESSAGE
              value: 'Powered by Insee Lab'
